version: "3.9"
services:

  ml-endpoint:
    build:
      context: .
      dockerfile: ../gew/mock_infrastructure/Dockerfile.mock
    command: uvicorn scenarios.tcw.mock_infrastructure.ml_endpoint:app --host 0.0.0.0 --port 8102
    ports:
      - "8102:8102"
    environment:
      - PYTHONPATH=/app

  channel-adapter:
    build:
      context: .
      dockerfile: ../gew/mock_infrastructure/Dockerfile.mock
    command: uvicorn scenarios.tcw.mock_infrastructure.channel_adapter:app --host 0.0.0.0 --port 8103
    ports:
      - "8103:8103"
    environment:
      - PYTHONPATH=/app
